{% set name = "flake8-black" %}
{% set version = "0.2.3" %}
{% set sha256 = "c199844bc1b559d91195ebe8620216f21ed67f2cc1ff6884294c91a0d2492684" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - flake8 >=3
    - black >=19.3b0
    - toml

test:
  commands:
    - 'flake8 --version | grep black:'

about:
  home: https://github.com/peterjc/flake8-black
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Extension for flake8 for validating Python code style using black
  dev_url: https://github.com/peterjc/flake8-black
  description: |
    Black, "The Uncompromising Code Formatter", is normally run to edit your
    Python code in place to match their coding style, a strict subset of the
    PEP 8 style guide. The point of this plugin is to be able to run
    black --check ... from within the flake8 plugin ecosystem. You might use
    this via a git pre-commit hook, or as part of your continuous integration
    testing.

extra:
  recipe-maintainers:
    - peterjc
